kind: AtlasDeployment
apiVersion: atlas.mongodb.com/v1
metadata:
  name: my-test-deployment
spec:
  projectRef:
    name: my-project
  advancedDeploymentSpec:
    clusterType: GEOSHARDED
    name: va-deployment
    replicationSpecs:
      - numShards: 1
        regionConfigs:
          - backingProviderName: AZURE
            electableSpecs:
              instanceSize: M30
              nodeCount: 3
            priority: 7
            providerName: AZURE
            regionName: EUROPE_NORTH
        zoneName: Zone1
      - numShards: 1
        regionConfigs:
          - backingProviderName: AWS
            electableSpecs:
              instanceSize: M30
              nodeCount: 3
            priority: 7
            providerName: AWS
            regionName: US_EAST_1
        zoneName: Zone2

