apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: atlas-deployment-mr-azure
spec:
  projectRef:
    name: my-project
  deploymentSpec:
    name: deployment-mr-azure
    providerBackupEnabled: true
    clusterType: REPLICASET
    providerSettings:
      instanceSizeName: M10
      providerName: AZURE
    replicationSpecs:
      - numShards: 1
        zoneName: Europe
        regionsConfig:
          NORWAY_EAST:
            analyticsNodes: 0
            electableNodes: 1
            priority: 6
            readOnlyNodes: 0
          GERMANY_NORTH:
            analyticsNodes: 0
            electableNodes: 2
            priority: 7
            readOnlyNodes: 0
